tony-gomes/adopt_dont_shop_2001_three_amigos

app/controllers/application_controller.rb, app/controllers/shelterpets_controller.rb, app/models/shelterpet.rb, app/views/shelterpets/index.html.erb
There were a few things Meg commented about during my project review.  I have corrected them in this PR so we can start with a base that's ready to go. I have done the following:
Removed an unnecessary shelterpet model
Added a previously removed forgery clause back into application controller
Fixed shelterpet_controller so it accesses pets through the shelter instead of separately
Fixed shelterpet.html.erb so it goes through the new pet path from the shelterpet_controller
All tests still pass and site still works.  Let me know if you have any questions!
=> Mvh base fixes

app/models/review.rb, app/models/shelter.rb, app/views/shelters/show.html.erb, db/migrate/20200324215431_create_reviews.rb, db/migrate/20200324220854_add_shelter_to_reviews.rb, db/schema.rb, spec/features/shelterreviews/shelter_review_index_spec.rb
- created reviews table
- created foreign key for shelters
- added test for
- reviews creation
- add reviews to shelter show page
- added reviews creation functionality
- added reviews to shelter show page
=> Jg shelter review us2

app/controllers/reviews_controller.rb, app/views/reviews/new.html.erb, app/views/shelters/show.html.erb, config/routes.rb, spec/features/shelterreviews/shelter_review_creation_spec.rb, spec/models/review_spec.rb
- add reviews create form test
- add reviews form
- still needs polishing (styling)
=> Jg review create us3

app/assets/stylesheets/application.css, app/controllers/reviews_controller.rb, app/views/reviews/new.html.erb, spec/features/shelterreviews/shelter_review_creation_cont_spec.rb
Create flash message for US3.
Adds flash message to review creation if review is invalid
Adds flash message style to CSS
Updates shelter review views
=> Mvh shelter review created ctd us4

app/controllers/reviews_controller.rb, app/views/reviews/edit.html.erb, app/views/shelters/show.html.erb, config/routes.rb, db/seeds.rb, spec/features/shelterreviews/shelter_reviews_edit_spec.rb
User Story 5, Edit/Update Review
- edit test
- link on shelters#show page
- edit/update controllers
- edit/update view
=> Tag edit shelter review us5

app/controllers/reviews_controller.rb, app/views/reviews/edit.html.erb, spec/features/shelterreviews/shelter_review_edit_cont_spec.rb
- add tests for adding flash to review edits with missing information
- add flash message functionality
=> Jg review edit flash us6

app/models/shelter.rb, app/views/reviews/edit.html.erb, spec/features/shelterreviews/shelter_review_edit_cont_spec.rb
Final debug
- Add destroy dependency to reviews in shelter model
- Add stateful for update review form
=> Group debug iteration 1

app/assets/stylesheets/application.css, app/controllers/application_controller.rb, app/controllers/favorite_controller.rb, app/controllers/pets_controller.rb, app/models/favorite.rb, app/views/layouts/application.html.erb, app/views/pets/show.html.erb, app/views/shelters/show.html.erb, config/routes.rb, spec/features/favorites/favorite_creation_spec.rb, spec/models/favorite_spec.rb
Create test and functionality to add pets as favorites.  All tests pass, model test for favorites have been made.  Model is  PORO.
Updates all functionality
Creates tests
Small changes made to views
Flash message made for pet favorite add
Stylesheets updated for flash message
=> Mvh favorite creation us9

app/controllers/favorite_controller.rb, app/views/favorite/index.html.erb, spec/features/favorites/favorite_index_page_spec.rb
This story completes US10.  Tests pass and functionality has been verified on rails s.
Tests will likely need to be beefed up but wanted to merge this into dev so I don't create a merge conflict when I merge in already created US11.  I will make all test changes on that one.
=> Create functionality for visiting favorites page

app/controllers/favorite_controller.rb, app/models/favorite.rb, app/views/favorite/index.html.erb, app/views/layouts/application.html.erb, config/routes.rb, spec/features/favorites/favorite_creation_spec.rb, spec/features/favorites/favorite_index_page_spec.rb, spec/features/favorites/favorite_indiciator_links_to_index_spec.rb, spec/features/pets/pet_links_spec.rb, spec/models/favorite_spec.rb
Add links to favorite page from favorite totals in nav bar.
All tests pass.
Add robustness to US9 and US10 tests.
Update model to accept optional arguments.
Update model test to test for those optional args.
=> Mvh fav links to index us11

app/controllers/favorite_controller.rb, app/models/favorite.rb, app/views/layouts/application.html.erb, app/views/pets/show.html.erb, config/routes.rb, spec/features/favorites/favorite_destroy_spec.rb, spec/features/favorites/favorite_index_page_spec.rb, spec/features/favorites/favorite_indiciator_links_to_index_spec.rb
=> Favorites cant duplicate us12

spec/features/favorites/remove_single_favorite_index_spec.rb
=> Add test for US13 for mass merge w/ US15

spec/features/favorites/no_pets_message_index_spec.rb
=> No pets message favorite index us14

app/assets/stylesheets/application.css, app/controllers/favorites_controller.rb, app/controllers/pet_applications_controller.rb, app/views/favorites/index.html.erb, app/views/layouts/application.html.erb, app/views/pet_applications/new.html.erb, app/views/pets/show.html.erb, app/views/reviews/edit.html.erb, app/views/reviews/new.html.erb, spec/features/applications/incomplete_application_spec.rb
Complete US17 with test and functionality.
Flash error message shows if required fields of application aren't filled out.
Moves flash messages into a site-wide location with standardized styling.
All controllers updated for new styling of flash messages.
All html pages have been fixed to use new location of flash message.
=> Mvh incomplete app us17

app/controllers/favorites_controller.rb, app/models/pet.rb, app/views/favorites/index.html.erb, app/views/reviews/new.html.erb, spec/features/applications/applying_for_a_pet_spec.rb, spec/features/applications/incomplete_application_spec.rb, spec/features/applications/list_of_pets_with_apps_spec.rb
Finish US18
Add test
Add list of pets with pending status
Remove favorite pets after adoption app has been put int
*Need to address issue of submitting an app with no pet
all tests pass
=> Mvh list of pets w aps us18

app/controllers/pet_applications_controller.rb, app/views/pet_applications/show.html.erb, config/routes.rb, spec/features/applications/application_show_spec.rb
added test for application show page
added application show page
=> add test, functionality for us19, pet application show page

app/controllers/pet_applications_controller.rb, app/views/favorites/index.html.erb, app/views/pet_applications/new.html.erb, app/views/pet_applications/show.html.erb, app/views/pets/show.html.erb, config/routes.rb, spec/features/applications/application_show_spec.rb, spec/features/applications/applying_for_a_pet_spec.rb, spec/features/applications/approve_application_spec.rb, spec/features/applications/incomplete_application_spec.rb, spec/features/applications/list_of_pets_with_apps_spec.rb
Fixed Pending status in create action for application
Add US22
=> Tag approving applications spec us22.rb

app/controllers/pet_applications_controller.rb, app/views/pet_applications/show.html.erb, config/routes.rb, spec/features/applications/application_show_spec.rb, spec/features/applications/approve_application_spec.rb
US 23 approve multiple pets
- add checkbox selection on application#show page
- update application controller to iterate pet_ids to update all included pets
- update affected test for change
=> Tag approve multiple pet applications us23.rb

app/views/pet_show_applications/index.html.erb, spec/features/applications/pet_show_apps_index_no_apps_spec.rb, spec/features/shelters/shelter_links_spec.rb
added short, sweet test for pets with and without applications
added function to add display for pets without applications
also fixed a spelling error in an older existing test that did not affect functionality.
=> Jg pet app index with no apps us21

app/controllers/favorites_controller.rb, app/controllers/pet_applications_controller.rb, app/models/shelter.rb, app/views/favorites/index.html.erb, app/views/shelters/show.html.erb, spec/features/applications/applictions_must_select_a_pet_spec.rb, spec/features/applications/applying_for_a_pet_spec.rb, spec/features/applications/incomplete_application_spec.rb, spec/features/shelters/shelter_stats_spec.rb
Somewhere along the lines US16 broke but tests weren't robust enough to catch it.  This PR will fix it and make it work again.
=> Mvh us16 patch

app/controllers/shelters_controller.rb, spec/features/shelters/shelter_crud_incomplete_flash_spec.rb
added tests for
* flash message for any/each fields left empty when creating a shelter
* flash message for any/each fields left empty when updating a shelter
added multiple flash message function for
* creating a shelter
* updating a shelter
=> Jg shelter crud incomplete flash us29

app/controllers/pets_controller.rb, app/controllers/shelterpets_controller.rb, app/views/pets/edit.html.erb, app/views/shelterpets/new.html.erb, spec/features/pets/pet_crud_incomplete_flash_spec.rb
added test for flash messages for incomplete fields for
* creating a pet
* editing a pet
added flash function to give multiple error messages
=> Jg pet crud incomplete flash us33
